services:
  backend:
    build: ./backend
    # env_file: ./backend/.env  # nur wenn du sie hast
    ports:
      - "127.0.0.1:5800:8000"   # nur lokal erreichbar
    restart: unless-stopped

  frontend:
    build: ./frontend
    depends_on: [backend]
    ports:
      - "127.0.0.1:5080:80"     # nur lokal erreichbar
    restart: unless-stopped