services:
  backend:
    build: ./backend
    # env_file: ./backend/.env  # nur wenn du sie hast
    environment:
      DATA_DIR: /data  
      KEYWORDS_PATH: /data/keywords.json
    volumes:
      - ./volumes/backend-data:/data
    ports:
      - "127.0.0.1:5800:8000"   # nur lokal erreichbar
    restart: unless-stopped

  frontend:
    build: ./frontend
    depends_on: [backend]
    ports:
      - "127.0.0.1:5080:80"     # nur lokal erreichbar
    restart: unless-stopped